const { resetTxt, boldTxt, settings } = require(`./config`)

let lastSansFace = 4

function getSansFace() {
    const sansExpressions = [
        sansOpenEyes,
        sansLookAround,
        sansWink,
        sansClosedEyes,
        sansNoEyes,
        sansSmall
    ]
    let expression = Math.floor(Math.random() * sansExpressions.length)
    while (expression === lastSansFace) {
        if (settings.debug) { console.log(`${boldTxt}> Re-rolling facial expression...${resetTxt}`) }
        expression = Math.floor(Math.random() * sansExpressions.length)
    }
    lastSansFace = expression
    sansExpressions[expression]()
}

function sansOpenEyes() {
    if (settings.debug) { console.log(`${boldTxt}> sansOpenEyes()${resetTxt}`) }
    const bkSq = `\x1b[40m  \x1b[0m`
    const whSq = `\x1b[47m  \x1b[0m`
    const noSq = `  `
    //          -1 -   -2 -   -3 -   -4 -   -5 -   -6 -   -7 -   -8 -   -9 -   -10-   -11-   -12-   -13-   -14-   -15-   -16-   -17-   -18-   -19-   -20-   -21-   -22-   -23-   -24-   -25-   -26-   -27-   -28-   -29-   -30-   -31-   -32-   -33-   -34-   -35-   -36-   -37-   -38-   -39-   -40-   -41-   -42-   -43-   -44-   -45-   -46-   -47-   -48-   -49-   -50-   -51-   -52-   -53-   -54-   -56-   -57-   -58-   -59-   -60-   -61-   -62-   -63-   -64-   -65-   -66-   -67-   -68-   -69-   -70-   -71-   -72-
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 1
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 2
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq) // 3
    console.log(noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq) // 4
    console.log(noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 5
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 6
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 7
    console.log(noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 8
    console.log(noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 9
    console.log(noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq) // 10
    console.log(whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq) // 11
    console.log(whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq) // 12
    console.log(whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq) // 13
    console.log(whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq) // 14
    console.log(whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq) // 15
    console.log(whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + noSq) // 16
    console.log(noSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + noSq) // 17
    console.log(noSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + noSq + noSq) // 18
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + noSq + noSq + noSq) // 19
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 20
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 21
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 22
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 23
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 24
    console.log(noSq + noSq + whSq + whSq + bkSq + bkSq + whSq + bkSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + noSq) // 25
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 26
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 27
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 28
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 29
    console.log(noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 30
    console.log(noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq) // 31
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq) // 32
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 33
}

function sansClosedEyes() {
    if (settings.debug) { console.log(`${boldTxt}> sansClosedEyes()${resetTxt}`) }
    const bkSq = `\x1b[40m  \x1b[0m`
    const whSq = `\x1b[47m  \x1b[0m`
    const noSq = `  `
    //          -1 -   -2 -   -3 -   -4 -   -5 -   -6 -   -7 -   -8 -   -9 -   -10-   -11-   -12-   -13-   -14-   -15-   -16-   -17-   -18-   -19-   -20-   -21-   -22-   -23-   -24-   -25-   -26-   -27-   -28-   -29-   -30-   -31-   -32-   -33-   -34-   -35-   -36-   -37-   -38-   -39-   -40-   -41-   -42-   -43-   -44-   -45-   -46-   -47-   -48-   -49-   -50-   -51-   -52-   -53-   -54-   -56-   -57-   -58-   -59-   -60-   -61-   -62-   -63-   -64-   -65-   -66-   -67-   -68-   -69-   -70-   -71-   -72-
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 1
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 2
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq) // 3
    console.log(noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq) // 4
    console.log(noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 5
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 6
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 7
    console.log(noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 8
    console.log(noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 9
    console.log(noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq) // 10
    console.log(whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq) // 11
    console.log(whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq) // 12
    console.log(whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq) // 13
    console.log(whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq) // 14
    console.log(whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq) // 15
    console.log(whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + noSq) // 16
    console.log(noSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + noSq) // 17
    console.log(noSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + noSq + noSq) // 18
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + noSq + noSq + noSq) // 19
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 20
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 21
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 22
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 23
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 24
    console.log(noSq + noSq + whSq + whSq + bkSq + bkSq + whSq + bkSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + noSq) // 25
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 26
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 27
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 28
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 29
    console.log(noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 30
    console.log(noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq) // 31
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq) // 32
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 33}
}

function sansNoEyes() {
    if (settings.debug) { console.log(`${boldTxt}> sansNoEyes()${resetTxt}`) }
    const bkSq = `\x1b[40m  \x1b[0m`
    const whSq = `\x1b[47m  \x1b[0m`
    const noSq = `  `
    //          -1 -   -2 -   -3 -   -4 -   -5 -   -6 -   -7 -   -8 -   -9 -   -10-   -11-   -12-   -13-   -14-   -15-   -16-   -17-   -18-   -19-   -20-   -21-   -22-   -23-   -24-   -25-   -26-   -27-   -28-   -29-   -30-   -31-   -32-   -33-   -34-   -35-   -36-   -37-   -38-   -39-   -40-   -41-   -42-   -43-   -44-   -45-   -46-   -47-   -48-   -49-   -50-   -51-   -52-   -53-   -54-   -56-   -57-   -58-   -59-   -60-   -61-   -62-   -63-   -64-   -65-   -66-   -67-   -68-   -69-   -70-   -71-   -72-
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 1
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 2
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq) // 3
    console.log(noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq) // 4
    console.log(noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 5
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 6
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 7
    console.log(noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 8
    console.log(noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 9
    console.log(noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq) // 10
    console.log(whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq) // 11
    console.log(whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq) // 12
    console.log(whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq) // 13
    console.log(whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq) // 14
    console.log(whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq) // 15
    console.log(whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + noSq) // 16
    console.log(noSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + noSq) // 17
    console.log(noSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + noSq + noSq) // 18
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + noSq + noSq + noSq) // 19
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 20
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 21
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 22
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 23
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 24
    console.log(noSq + noSq + whSq + whSq + bkSq + bkSq + whSq + bkSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + noSq) // 25
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 26
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 27
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 28
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 29
    console.log(noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 30
    console.log(noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq) // 31
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq) // 32
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 33
}

function sansWink() {
    if (settings.debug) { console.log(`${boldTxt}> sansWink()${resetTxt}`) }
    const bkSq = `\x1b[40m  \x1b[0m`
    const whSq = `\x1b[47m  \x1b[0m`
    const noSq = `  `
    //          -1 -   -2 -   -3 -   -4 -   -5 -   -6 -   -7 -   -8 -   -9 -   -10-   -11-   -12-   -13-   -14-   -15-   -16-   -17-   -18-   -19-   -20-   -21-   -22-   -23-   -24-   -25-   -26-   -27-   -28-   -29-   -30-   -31-   -32-   -33-   -34-   -35-   -36-   -37-   -38-   -39-   -40-   -41-   -42-   -43-   -44-   -45-   -46-   -47-   -48-   -49-   -50-   -51-   -52-   -53-   -54-   -56-   -57-   -58-   -59-   -60-   -61-   -62-   -63-   -64-   -65-   -66-   -67-   -68-   -69-   -70-   -71-   -72-
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 1
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 2
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq) // 3
    console.log(noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq) // 4
    console.log(noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 5
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 6
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 7
    console.log(noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 8
    console.log(noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 9
    console.log(noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq) // 10
    console.log(whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq) // 11
    console.log(whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq) // 12
    console.log(whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq) // 13
    console.log(whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq) // 14
    console.log(whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq) // 15
    console.log(whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + noSq) // 16
    console.log(noSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + noSq) // 17
    console.log(noSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + noSq + noSq) // 18
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 19
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 20
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 21
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 22
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 23
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 24
    console.log(noSq + noSq + whSq + whSq + bkSq + bkSq + whSq + bkSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + noSq) // 25
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 26
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 27
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 28
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 29
    console.log(noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 30
    console.log(noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq) // 31
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq) // 32
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 33
}

function sansLookAround() {
    if (settings.debug) { console.log(`${boldTxt}> sansLookAround()${resetTxt}`) }
    const bkSq = `\x1b[40m  \x1b[0m`
    const whSq = `\x1b[47m  \x1b[0m`
    const noSq = `  `
    //          -1 -   -2 -   -3 -   -4 -   -5 -   -6 -   -7 -   -8 -   -9 -   -10-   -11-   -12-   -13-   -14-   -15-   -16-   -17-   -18-   -19-   -20-   -21-   -22-   -23-   -24-   -25-   -26-   -27-   -28-   -29-   -30-   -31-   -32-   -33-   -34-   -35-   -36-   -37-   -38-   -39-   -40-   -41-   -42-   -43-   -44-   -45-   -46-   -47-   -48-   -49-   -50-   -51-   -52-   -53-   -54-   -56-   -57-   -58-   -59-   -60-   -61-   -62-   -63-   -64-   -65-   -66-   -67-   -68-   -69-   -70-   -71-   -72-
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 1
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 2
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq) // 3
    console.log(noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq) // 4
    console.log(noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 5
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 6
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 7
    console.log(noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 8
    console.log(noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 9
    console.log(noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq) // 10
    console.log(whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq) // 11
    console.log(whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq) // 12
    console.log(whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq) // 13
    console.log(whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq) // 14
    console.log(whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq) // 15
    console.log(whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + noSq) // 16
    console.log(noSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + noSq) // 17
    console.log(noSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + noSq + noSq) // 18
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 19
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 20
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 21
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 22
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 23
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 24
    console.log(noSq + noSq + whSq + whSq + bkSq + bkSq + whSq + bkSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + noSq) // 25
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 26
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq) // 27
    console.log(noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 28
    console.log(noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq) // 29
    console.log(noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq) // 30
    console.log(noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq) // 31
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq) // 32
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 33
}

function sansSmall() {
    if (settings.debug) { console.log(`${boldTxt}> sansSmall()${resetTxt}`) }
    const bkSq = `\x1b[40m  \x1b[0m`
    const whSq = `\x1b[47m  \x1b[0m`
    const blSq = `\x1b[44m  \x1b[0m`
    const gySq = `\x1b[100m  \x1b[0m`
    const noSq = `  `
    //          -1 -   -2 -   -3 -   -4 -   -5 -   -6 -   -7 -   -8 -   -9 -   -10-   -11-   -12-   -13-   -14-   -15-   -16-   -17-   -18-   -19-   -20-   -21-   -22-   -23-
    console.log(noSq + noSq + noSq + noSq + noSq + noSq + noSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq) // 1
    console.log(noSq + noSq + noSq + noSq + noSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + noSq + noSq + noSq + noSq + noSq) // 2
    console.log(noSq + noSq + noSq + noSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + noSq + noSq + noSq + noSq) // 3
    console.log(noSq + noSq + noSq + noSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + noSq + noSq + noSq + noSq) // 4
    console.log(noSq + noSq + noSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + noSq + noSq + noSq) // 5
    console.log(noSq + noSq + noSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + bkSq + noSq + noSq + noSq) // 6
    console.log(noSq + noSq + noSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + bkSq + noSq + noSq + noSq) // 7
    console.log(noSq + noSq + noSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + bkSq + noSq + noSq + noSq) // 8
    console.log(noSq + noSq + noSq + noSq + bkSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + bkSq + noSq + noSq + noSq + noSq) // 9
    console.log(noSq + noSq + noSq + bkSq + bkSq + whSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + whSq + bkSq + bkSq + noSq + noSq + noSq) // 10
    console.log(noSq + noSq + noSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + bkSq + noSq + noSq + noSq) // 11
    console.log(noSq + noSq + noSq + bkSq + whSq + whSq + whSq + bkSq + whSq + bkSq + whSq + bkSq + whSq + bkSq + whSq + bkSq + whSq + whSq + whSq + bkSq + noSq + noSq + noSq) // 12
    console.log(noSq + noSq + noSq + noSq + bkSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + bkSq + bkSq + noSq + noSq + noSq + noSq) // 13
    console.log(noSq + noSq + noSq + bkSq + bkSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + bkSq + bkSq + noSq + noSq + noSq) // 14
    console.log(noSq + noSq + bkSq + blSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + blSq + bkSq + noSq + noSq) // 15
    console.log(noSq + bkSq + bkSq + blSq + bkSq + gySq + gySq + bkSq + whSq + whSq + whSq + bkSq + whSq + whSq + whSq + bkSq + gySq + gySq + bkSq + blSq + bkSq + bkSq + noSq) // 16
    console.log(noSq + bkSq + blSq + blSq + blSq + bkSq + gySq + gySq + bkSq + bkSq + bkSq + whSq + bkSq + bkSq + bkSq + gySq + gySq + bkSq + blSq + blSq + blSq + bkSq + noSq) // 17
    console.log(bkSq + blSq + blSq + bkSq + bkSq + blSq + bkSq + bkSq + bkSq + whSq + whSq + bkSq + whSq + whSq + bkSq + bkSq + bkSq + blSq + bkSq + bkSq + blSq + blSq + bkSq) // 18
    console.log(bkSq + blSq + blSq + blSq + blSq + bkSq + blSq + blSq + bkSq + whSq + whSq + whSq + whSq + whSq + bkSq + blSq + blSq + bkSq + blSq + blSq + blSq + blSq + bkSq) // 19
    console.log(bkSq + blSq + blSq + blSq + blSq + blSq + bkSq + blSq + bkSq + bkSq + whSq + whSq + whSq + bkSq + bkSq + blSq + bkSq + blSq + blSq + blSq + blSq + blSq + bkSq) // 20
    console.log(noSq + bkSq + blSq + blSq + blSq + bkSq + blSq + blSq + bkSq + whSq + whSq + whSq + whSq + whSq + bkSq + blSq + blSq + bkSq + blSq + blSq + blSq + bkSq + noSq) // 21
    console.log(noSq + noSq + bkSq + bkSq + blSq + bkSq + blSq + blSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + blSq + blSq + bkSq + blSq + bkSq + bkSq + noSq + noSq) // 22
    console.log(noSq + noSq + noSq + bkSq + bkSq + bkSq + blSq + blSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + blSq + blSq + bkSq + bkSq + bkSq + noSq + noSq + noSq) // 23
    console.log(noSq + noSq + noSq + noSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + noSq + noSq + noSq + noSq) // 24
    console.log(noSq + noSq + noSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + noSq + noSq + noSq) // 25
    console.log(noSq + noSq + noSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + noSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + noSq + noSq + noSq) // 26
    console.log(noSq + noSq + noSq + noSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + noSq + noSq + noSq + bkSq + bkSq + bkSq + bkSq + bkSq + bkSq + noSq + noSq + noSq + noSq) // 27
    console.log(noSq + noSq + bkSq + bkSq + bkSq + whSq + whSq + whSq + whSq + bkSq + noSq + noSq + noSq + bkSq + whSq + whSq + whSq + whSq + bkSq + bkSq + bkSq + noSq + noSq) // 28
    console.log(noSq + noSq + bkSq + whSq + whSq + whSq + whSq + whSq + bkSq + bkSq + noSq + noSq + noSq + bkSq + bkSq + whSq + whSq + whSq + whSq + whSq + bkSq + noSq + noSq) // 29
    console.log(noSq + noSq + noSq + bkSq + bkSq + bkSq + bkSq + bkSq + noSq + noSq + noSq + noSq + noSq + noSq + noSq + bkSq + bkSq + bkSq + bkSq + bkSq + noSq + noSq + noSq) // 30
}

module.exports = { getSansFace }
